name: CI Pipeline

# 定义何时触发工作流：在 push 和 pull request 时
on:
  push:
    branches:
      - main
      - feature/*
  pull_request:
    branches:
      - main

# 定义工作流运行的环境和步骤
jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: ['3.9']  # 设置 Python 版本
        node-version: ['16.x']   # 设置 Node.js 版本

    steps:
    # 1. 检出代码库
    - name: Checkout repository
      uses: actions/checkout@v2

    # 2. 设置 Python 环境
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}

    # 3. 安装 Python 依赖 (后端)
    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r backend/requirements.txt

    # 4. 运行后端测试
    - name: Run backend tests
      run: |
        pytest backend/tests

    # 5. 设置 Node.js 环境
    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}

    # 6. 安装前端依赖
    - name: Install frontend dependencies
      working-directory: frontend
      run: npm install

    # 7. 运行前端测试
    - name: Run frontend tests
      working-directory: frontend
      run: npm test

    # 8. 构建前端项目
    - name: Build frontend
      working-directory: frontend
      run: npm run build
